name: cfr2

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v4
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: upload
          destination-dir: ./
          output-file-url: 'true'
      
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
